### ISSUE TITLE
Criar template no GitHub pages para o PHPDF

### ISSUE THREAD

**Issue by oviniciusfeitosa** [php-df/php-df.github.io#1]
- [x] Avaliar a possibilidade de utilizar um gerador de site estático:
    https://jekyllrb.com/
    https://sculpin.io/
- [x] Criar template no GitHub pages para o PHPDF

**Comment by raniery** [comment]
Avaliar a possibilidade de utilizar um gerador de site estático:
https://jekyllrb.com/
https://sculpin.io/
