### ISSUE TITLE
Criar um "ver mais" no quadro de eventos

### ISSUE THREAD

**Issue by raniery** [php-df/php-df.github.io#38]
Criar um "ver mais" no quadro de eventos

**Comment by oviniciusfeitosa** [comment]
Beleza, para qual link o "Ver mais" deve apontar?

**Comment by leonnleite** [comment]
@vinnyfs89 até onde eu entendi, esse novo link tem que ser implementado também.

Hoje mostra todos os eventos, quando tivermos 100 cadastrados, a ideia é mostrar uns 4, e no ver mais... mostrar os antigos

**Comment by leonnleite** [comment]
Vou fechar para fazermos a dinamica com o ingresso do PHPx
